

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      dialect:

  datasource:
    driver: org.h2.Driver
    platform: hsqldb
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: