server:
    port: 8080

spring:
    jackson:
      property-naming-strategy: SNAKE_CASE
    jpa:
      database: POSTGRESQL
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
